### ISSUE TITLE
Corrupted ZIP files

### ISSUE THREAD

**Issue by martusi61** [lyovav/ESP8266-Max7219#1]
Hi, I've tried to download the Firmware_ESP8266_v228.7.zip file, but as all your .zips won't open due to the "file is not valid" error, I would have liked to have a look at your project.

**Comment by v222008** [comment]
> Hi, I've tried to download the Firmware_ESP8266_v228.7.zip file, but as all your .zips won't open due to the "file is not valid" error, I would have liked to have a look at your project.

Use winrar 6.11 or higher opens the archive successfully.  
![Без імені](https://user-images.githubusercontent.com/4614427/223687852-dac46ca9-618d-4f35-b2da-210b32dba0d1.jpg)

**Comment by martusi61** [comment]
Thanks, it actually worked, but why don't you normalize the zip file so that everyone can open it even without WinRAR? I'll take a look at your nice firmware and let you know.

**Comment by lyovav** [comment]
Unfortunately, the firmware is not my personal one, I lost contact with the author. but some functionality is still working. I have a purchased winrar and I didn't even think about it

**Comment by lyovav** [comment]
need winrar 6.11 or higher
